### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by abigkeep** [NCZkevin/chatglm-web#5]
使用[https://github.com/THUDM/ChatGLM-6B](url)的后端api和此项目的前端。
后端报错显示如下
   INFO:     Started server process [7348]
   INFO:     Waiting for application startup.
   INFO:     Application startup complete.
   INFO:     Uvicorn running on http://0.0.0.0:3002 (Press CTRL+C to quit)
   INFO:     127.0.0.1:50608 - "POST /chat-process HTTP/1.1" 404 Not Found
   INFO:     127.0.0.1:50609 - "POST /chat-process HTTP/1.1" 404 Not Found
前端报错如下：
  2023/4/16 15:03:40 ：你好

  2023/4/16 15:03:40：Request failed with status code 404

如何解决

**Comment by NCZkevin** [comment]
和官方的API实现有一点区别，没有办法直接使用，看效果的话先用本项目的后端吧在service目录下
